### ISSUE TITLE
"function Is-Empty-Str" & "function Is-Even" is invalid in "./scripts/optional_helpers/interrupt_affinity_auto.ps1"

### ISSUE THREAD

**Issue by danielwuaustralia** [dougg0k/gaming_os_tweaker#11]
function Is-Empty-Str {
	param ([string] $value)
	[string]::IsNullOrWhiteSpace($value)
}

function Is-Even {
	param ([int] $value)
	$value % 2 -eq 0
}

**The cmdlet 'Is-Empty-Str' uses an unapproved verb.**
**The cmdlet 'Is-Even' uses an unapproved verb.**
it points to https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/UseApprovedVerbs?view=ps-modules

**Comment by dougg0k** [comment]
It's not meant to be in the good practices, since it's just a small script, it has bad code in most parts of it. It should still be working. But you can submit a PR if you want, correcting it.
