### ISSUE TITLE
Automate the disabling of interrupt moderation in usb

### ISSUE THREAD

**Issue by dougg0k** [dougg0k/gaming_os_tweaker#12]
https://github.com/djdallmann/GamingPCSetup/tree/master/CONTENT/RESEARCH/PERIPHERALS#universal-serial-bus-usb

https://www.overclock.net/threads/usb-polling-precision.1550666/page-61

https://forums.blurbusters.com/viewtopic.php?t=11863

https://github.com/BoringBoredom/PC-Optimization-Hub/blob/main/content/xhci%20imod/xhci%20imod.md

**Comment by dougg0k** [comment]
I was able to build the script, but just like the message I left at the top of the script. I am unable to test the script, if worked and is correct or not.

https://github.com/dougg0k/gaming_os_tweaker/commit/b205ebff12e2c2bc851cfc855b3b7a7910fb0328

Maybe if an alternative tool instead of rweverything is found or someone else are able to test.

**Comment by dougg0k** [comment]
On the last post of the overlock.net forum, someone recommended https://github.com/Faintsnow/HE

**Comment by dougg0k** [comment]
I was able to resolve and finish the script for intel, but not yet amd.

**Comment by andrelip** [comment]
About the mouse part, I had to change the moderations of "USB 3.20 eXtensible Host Controller..." for it to work appropriately (front USB port).

A way to ensure it's working is by opening latencymon, stopping moving the mouse, observing the ISR count, then starting moving it fast in circles and checking the processor has the increased ISR. In my case, it was processed by wdf0100.sys.

**Comment by amitxv** [comment]
I am interested in helping and experimenting further on this topic, but I have a few questions to better understand your script. Do you have Discord?

**Comment by dougg0k** [comment]
I dont really use discord much. It's the same as my github. 

I dont really understand much about the subject itself, that is why I been asking for help to be able to build the proper implementation, but there are still questions that need answering, the current discussion are happening here https://github.com/djdallmann/GamingPCSetup/issues/12

Current implementation is not correct it seems, BoringBoredom even updated his guide to help. https://github.com/BoringBoredom/PC-Optimization-Hub/blob/main/content/xhci%20imod/xhci%20imod.md

**Comment by amitxv** [comment]
No problem, we can discuss on the existing thread.

**Comment by dougg0k** [comment]
It's done. 

https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/optional_helpers/interrupt_moderation_usb.ps1
