### ISSUE TITLE
Fps locked to refresh rate in win11 only

### ISSUE THREAD

**Issue by dougg0k** [dougg0k/gaming_os_tweaker#13]
There is an issue that happens on Win11 only and in certain DX11 games only that I know, so far.

One main game that this happens is Overwatch 2.

The fps stay locked to your refresh rate in fullscreen or borderless fullscreen, only in windowed mode it unlocks and reaches the max you have set.

I then found something, if I disable optimized for windowed games, I can run in borderless fullscreen and window mode with the fps that I set (fully unlocked), but fullscreen mode are still being locked. However, if I enable, I can only have the fps fully unlocked in window mode.

Not sure why they would do this, but it's clearly broken and not only with Overwatch. If you have Gsync/Freesync, you have to turn it on to unlock fps in any display mode, that breaks the point of anti-blur/BFI tech like ULMB. This is confirmed.

---

https://www.reddit.com/r/blackdesertonline/comments/xq9sq6/for_those_interested_win11_22h2_is_now_available/
https://www.reddit.com/r/blackdesertonline/comments/xk7ixg/psa_windows_11_users_may_now_uncap_fps_in/

I have tested two DX12, one MP and other SP, the problem did not happen. 

Overwatch 2 are DX11 only and Black Desert are DX11 only.

I also tested another MP game in DX11 (Apex Legends) and the problem does not happen there. It seems to be a problem with certain DX11 games only.

---

I reported the issue to git DX11 SDK, but they said it was a problem in the game. https://github.com/microsoft/DirectXTK/issues/395

---

Someone reported to have fixed a similar issue by removing some tweaks / reg changes. https://forums.blurbusters.com/viewtopic.php?f=10&t=12148&sid=c08db230af63a14b3485da10ade328fc&start=10

However, I tested this problem before If I remember correctly, in a non tweaked version of Win11 post install, and the problem was still there.

---

I created a thread to see if anyone know anything. https://forums.blurbusters.com/viewtopic.php?f=10&t=12218

**Comment by dougg0k** [comment]
Know anything about this? @amitxv @BoringBoredom

**Comment by dougg0k** [comment]
I confirmed what was causing in this case. What that person reported in the blurbuster forum was somewhat accurate. But it was only one reg causing it.

To fix, remove the reg
```
REG DELETE "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\Scheduler" /v ForceFlipTrueImmediateMode /f
```

**Comment by sherifmagdy32** [comment]
> There is an issue that happens on Win11 only and in certain DX11 games only that I know, so far.
> 
> One main game that this happens is Overwatch 2.
> 
> The fps stay locked to your refresh rate in fullscreen or borderless fullscreen, only in windowed mode it unlocks and reaches the max you have set.
> 
> I then found something, if I disable optimized for windowed games, I can run in borderless fullscreen and window mode with the fps that I set (fully unlocked), but fullscreen mode are still being locked. However, if I enable, I can only have the fps fully unlocked in window mode.
> 
> Not sure why they would do this, but it's clearly broken and not only with Overwatch. If you have Gsync/Freesync, you have to turn it on to unlock fps in any display mode, that breaks the point of anti-blur/BFI tech like ULMB. This is confirmed.
> 
> https://www.reddit.com/r/blackdesertonline/comments/xq9sq6/for_those_interested_win11_22h2_is_now_available/ https://www.reddit.com/r/blackdesertonline/comments/xk7ixg/psa_windows_11_users_may_now_uncap_fps_in/
> 
> I have tested two DX12, one MP and other SP, the problem did not happen.
> 
> Overwatch 2 are DX11 only and Black Desert are DX11 only.
> 
> I also tested another MP game in DX11 (Apex Legends) and the problem does not happen there. It seems to be a problem with certain DX11 games only.
> 
> I reported the issue to git DX11 SDK, but they said it was a problem in the game. [microsoft/DirectXTK#395](https://github.com/microsoft/DirectXTK/issues/395)
> 
> Someone reported to have fixed a similar issue by removing some tweaks / reg changes. https://forums.blurbusters.com/viewtopic.php?f=10&t=12148&sid=c08db230af63a14b3485da10ade328fc&start=10
> 
> However, I tested this problem before If I remember correctly, in a non tweaked version of Win11 post install, and the problem was still there.
> 
> I created a thread to see if anyone know anything. https://forums.blurbusters.com/viewtopic.php?f=10&t=12218

I had something similar in fortnite when i tab out it is like it turns on vsync after i removed the registry key it went away.
