### ISSUE TITLE
Look into adding functional dwm disable scripts for win10 and 11

### ISSUE THREAD

**Issue by dougg0k** [dougg0k/gaming_os_tweaker#15]
Should:
- Contain detailed guide and a way to enable / disable as in disable and recover.
- Be tested in both Win10 and 11 (22H2).
- Be a standalone, meaning it should contain everything that it needs to work and recover.
- Be a toggle, single script - cmd or ps1

---

Refs:

https://github.com/Ingan121/DWMKiller/tree/master/ko/Win11
https://github.com/amitxv/PC-Tuning/tree/main/bin/scripts/dwm-scripts
https://winclassic.net/thread/1381/dwm-windows-mouse-cursor-disappearing
https://github.com/AndreyRGW/DisableDWM

**Comment by UseUrSk1lz** [comment]
is impossible to recover with usermode script if something was to go wrong as you would be left with a black screen. 

Script could add a smaller recovery script to the computer startup folder and it would wait x ammount of time before reverting everything and restart once again.

you would need to call higher privalleges than admin to disable the dwm in usermode in the first place
would be hard to make but possible...

**Comment by dougg0k** [comment]
Of course a way to make it work would be included. But to the point, nothing is currently working on Win11 22H2, so for now there wont be anything done. 

One way would be on the startup, another would be to do build checks, let it run only in the builds that were tested and confirmed working.

**Comment by dougg0k** [comment]
Progress at https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/optional_helpers/dwm.ps1

**Comment by dougg0k** [comment]
I built the script, it's fully automated, but currently only working on win10. https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/optional_helpers/dwm.ps1
