### ISSUE TITLE
Closes only valorant

### ISSUE THREAD

**Issue by Ghrants** [dougg0k/gaming_os_tweaker#22]
I was playing a game in valorant and in the middle of the game the game closed, for a moment I thought it was my PC, I checked temperatures, disk, and even reinstalled the OS and applied all the steps again and the same thing happened, not always It closes for me but it usually happens, any idea what it could be?  this does not happen in a normal OS

**Comment by dougg0k** [comment]
Unless there is an error to indicate something, hard to know. Check their anti cheat logs to see if there is anything there. Otherwise you're better off searching on google.

**Comment by GAZASTRIP** [comment]
> I was playing a game in valorant and in the middle of the game the game closed, for a moment I thought it was my PC, I checked temperatures, disk, and even reinstalled the OS and applied all the steps again and the same thing happened, not always It closes for me but it usually happens, any idea what it could be? this does not happen in a normal OS

Try turn Virtualization Technology back on fixed it for me
