### ISSUE TITLE
Power Lost to Usb ports and Keyboard and Mouse after Services script run

### ISSUE THREAD

**Issue by GAZASTRIP** [dougg0k/gaming_os_tweaker#27]

**Comment by dougg0k** [comment]
No idea what service could be causing your issue, if you find out, let me know and I will make the change. Your case might be very specific.

**Comment by dougg0k** [comment]
Were you able to find what service were causing it? 

Otherwise I will close the issue, since I have no way to find out, since the problem are specifically happening in your machine.
