### ISSUE TITLE
all game process that start from steam is set to belownormal priority 

### ISSUE THREAD

**Issue by chuchufran** [dougg0k/gaming_os_tweaker#28]
it should be normal priority or im wrong?

**Comment by dougg0k** [comment]
You should ask steam.

**Comment by chuchufran** [comment]
its happend when i apply ur script

**Comment by dougg0k** [comment]
My script does not messes with games from steam, only steam processes, that you can find in this small list. 

https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/tweaks/processes.cmd#L19

**Comment by chuchufran** [comment]
Thanks , keep up ur great work bro
