### ISSUE TITLE
laptop options

### ISSUE THREAD

**Issue by 3zap** [dougg0k/gaming_os_tweaker#8]
are you able to add a new debloating options for laptop

**Comment by dougg0k** [comment]
What debloat options do you mean?

**Comment by dougg0k** [comment]
I'm not sure what you mean by damage, there are tweaks that are not debloat and do make changes power settings that are not for laptops, and are only done to what is not on battery. 

Regardless, I dont really have a windows laptop nor the time to test specific settings. So, no.

You must read what I wrote in the README, that is the goal of the scripts here, not make specific changes for specific needs of users. And this was mostly built/compiled for myself, I just decided to share. 

Currently the work is for PCs only, at least from my end. It doesnt mean it wont work on laptops.
